configured_endpoints: 19
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/algo724-d1zj1l%2Fcadenza-client-sdk-59dda8c722afe4c3c6e59a076533e351db55e9ed98dd6a3c3ae8336a90b88686.yml
